/*
 * open-api-java
 * tlink-open-api-sdk
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tlink.openapi.api;

import com.tlink.openapi.invoker.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AlarmsControllerApi
 */
@Disabled
public class AlarmsControllerApiTest {

    private final AlarmsControllerApi api = new AlarmsControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void activeAlarmsTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.activeAlarms(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addAlarmsTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.addAlarms(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAlarmsTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.deleteAlarms(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteContactTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.deleteContact(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteContactsTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.deleteContacts(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAlarmsTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getAlarms(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAlarmsHistoryTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getAlarmsHistory(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllContactsTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getAllContacts(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getContactByIdTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getContactById(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void reBindWeChatTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.reBindWeChat(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void saveContactTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.saveContact(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAlarmsTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.updateAlarms(requestBody);
        // TODO: test validations
    }

}
