/*
 * open-api-java
 * tlink-open-api-sdk
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tlink.openapi.api;

import com.tlink.openapi.invoker.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeviceControllerApi
 */
@Disabled
public class DeviceControllerApiTest {

    private final DeviceControllerApi api = new DeviceControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addDeviceTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.addDevice(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addDeviceGroupTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.addDeviceGroup(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteDeviceTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.deleteDevice(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteDeviceGroupTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.deleteDeviceGroup(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deviceWriteTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.deviceWrite(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDeviceGroupTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getDeviceGroup(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDeviceSensorDatasTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getDeviceSensorDatas(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDevicesTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getDevices(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getModbusTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getModbus(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getParamsTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getParams(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProtocolLabelTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getProtocolLabel(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSensorHistroyTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getSensorHistroy(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSensorMappingTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getSensorMapping(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSingleDeviceDatasTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getSingleDeviceDatas(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSingleSensorDatasTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getSingleSensorDatas(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendDatapointTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.sendDatapoint(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setFlagTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.setFlag(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setModbusTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.setModbus(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setMqttTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.setMqtt(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setParamsTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.setParams(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setProtocolLabelTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.setProtocolLabel(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void switcherControllerTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.switcherController(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateDeviceTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.updateDevice(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateDeviceGroupTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.updateDeviceGroup(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateModbusTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.updateModbus(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateUserInfo1Test() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.updateUserInfo1(requestBody);
        // TODO: test validations
    }

}
