/*
 * open-api-java
 * tlink-open-api-sdk
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tlink.openapi.api;

import com.tlink.openapi.invoker.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SchedulerControllerApi
 */
@Disabled
public class SchedulerControllerApiTest {

    private final SchedulerControllerApi api = new SchedulerControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void activeSchedulerTest() throws ApiException {
        String body = null;
        String response = api.activeScheduler(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addSchedulerTest() throws ApiException {
        String body = null;
        String response = api.addScheduler(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSchedulerTest() throws ApiException {
        String body = null;
        String response = api.deleteScheduler(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSchedulerTest() throws ApiException {
        String jsonStr = null;
        String response = api.getScheduler(jsonStr);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSchedulerTest() throws ApiException {
        String body = null;
        String response = api.updateScheduler(body);
        // TODO: test validations
    }

}
