/*
 * open-api-java
 * tlink-open-api-sdk
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tlink.openapi.api;

import com.tlink.openapi.invoker.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserControllerApi
 */
@Disabled
public class UserControllerApiTest {

    private final UserControllerApi api = new UserControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserInfoTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getUserInfo(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVerifyCodeTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getVerifyCode(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePasswordTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.updatePassword(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateUserInfoTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.updateUserInfo(requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userLoginTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.userLogin(requestBody);
        // TODO: test validations
    }

}
