/*
 * open-api-java
 * tlink-open-api-sdk
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tlink.openapi.api;

import com.tlink.openapi.invoker.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for YunzutaiControllerApi
 */
@Disabled
public class YunzutaiControllerApiTest {

    private final YunzutaiControllerApi api = new YunzutaiControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getYunzutaiListTest() throws ApiException {
        Map<String, Object> requestBody = null;
        String response = api.getYunzutaiList(requestBody);
        // TODO: test validations
    }

}
